# Generated by Django 4.0.4 on 2022-05-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('putovanja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korisnik',
            name='ime',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='korisnik',
            name='prezime',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='korisnik',
            name='profilna_slika',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
