# Generated by Django 4.0.4 on 2022-05-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('putovanja', '0002_alter_korisnik_ime_alter_korisnik_prezime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agencija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('id_agencije', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('profilna_slika', models.CharField(max_length=250, null=True)),
                ('datum_osnivanja', models.DateField(null=True)),
            ],
        ),
    ]
