# Generated by Django 4.0.4 on 2022-05-13 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('putovanja', '0003_agencija'),
    ]

    operations = [
        migrations.CreateModel(
            name='Putovanje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=200)),
                ('lokacija', models.CharField(max_length=80)),
                ('slika', models.CharField(max_length=200)),
                ('kratak_opis', models.CharField(max_length=500)),
                ('cijena', models.FloatField()),
                ('datum_putovanja', models.DateField()),
                ('tip_putovanja', models.CharField(max_length=30)),
                ('prevoz', models.CharField(max_length=40)),
                ('maks_prijava', models.IntegerField()),
                ('min_prijava', models.IntegerField()),
                ('latituda', models.FloatField()),
                ('longituda', models.FloatField()),
                ('id_agencije', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='putovanja.agencija')),
            ],
        ),
    ]
