# Generated by Django 4.0.4 on 2022-05-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('putovanja', '0004_putovanje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencija',
            name='profilna_slika',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='korisnik',
            name='profilna_slika',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='putovanje',
            name='slika',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
