# Generated by Django 4.0.4 on 2022-05-14 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('putovanja', '0005_alter_agencija_profilna_slika_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='putovanje',
            old_name='id_agencije',
            new_name='agencija',
        ),
    ]
