# Generated by Django 4.0.4 on 2022-05-14 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('putovanja', '0006_rename_id_agencije_putovanje_agencija'),
    ]

    operations = [
        migrations.CreateModel(
            name='Putovanja_korisnika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='putovanja.korisnik')),
                ('putovanje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='putovanja.putovanje')),
            ],
        ),
    ]
