# Generated by Django 4.0.4 on 2022-05-30 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('putovanja', '0007_putovanja_korisnika'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zahtjevi_putovanja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lokacija', models.CharField(max_length=70)),
                ('datum', models.DateField()),
                ('prevoz', models.CharField(max_length=30)),
                ('cijena', models.FloatField()),
                ('agencija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='putovanja.agencija')),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='putovanja.korisnik')),
            ],
        ),
    ]
