# Generated by Django 4.0.4 on 2022-05-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('putovanja', '0008_zahtjevi_putovanja'),
    ]

    operations = [
        migrations.AddField(
            model_name='zahtjevi_putovanja',
            name='korisnik_username',
            field=models.CharField(default='Kerim', max_length=70),
            preserve_default=False,
        ),
    ]
