# Generated by Django 4.0.4 on 2022-06-04 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('putovanja', '0009_zahtjevi_putovanja_korisnik_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='zahtjevi_putovanja',
            name='latituda',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='zahtjevi_putovanja',
            name='longituda',
            field=models.FloatField(null=True),
        ),
    ]
