# Generated by Django 4.0.4 on 2022-06-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('putovanja', '0010_zahtjevi_putovanja_latituda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencija',
            name='profilna_slika',
            field=models.ImageField(default='images/profilna_default.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='korisnik',
            name='profilna_slika',
            field=models.ImageField(default='images/profilna_default.png', null=True, upload_to='images/'),
        ),
    ]
